syntax = "proto3";

package spine.examples.projects;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.projects";

// Requests a new project.
message CreateProject {
  // Uniquely identifies the new project.
  string id = 1 [(required) = true];

  // A name for the project.
  string name = 2 [(required) = true];
}

// Requests a new task.
message CreateTask {
  // Uniquely identifies the new task.
  string id = 1 [(required) = true];

  // The project containing the task.
  string project_id = 2 [(required) = true];
}

// Requests registration of a person.
message EnrollPerson {
  // Uniquely identifies the enrolled person.
  string id = 1 [(required) = true];

  // A name for the person.
  string display_name = 2 [(required) = true];
}
