syntax = "proto3";
package spine.example.datastore_orders.v1;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.example.datastore-orders";

// Represents an order aggregate.
message Order {
  option (entity).kind = AGGREGATE;
  // Holds the immutable identifier assigned to this order.
  string id = 1 [(required) = true, (set_once) = true];
  // Identifies the ordered SKU.
  string sku_id = 2 [(required) = true];
}

// Represents a SKU aggregate.
message Sku {
  option (entity).kind = AGGREGATE;
  // Holds the immutable identifier assigned to this SKU.
  string id = 1 [(required) = true, (set_once) = true];
  // Provides the SKU name shown to users.
  string display_name = 2 [(required) = true];
}
