syntax = "proto3";
package spine.example.datastore_orders.v1;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.example.datastore-orders";

// Records that an order was created.
message OrderCreated {
  // Identifies the created order.
  string id = 1 [(required) = true];
  // Identifies the ordered SKU.
  string sku_id = 2 [(required) = true];
}

// Records that a SKU was registered.
message SkuRegistered {
  // Identifies the registered SKU.
  string id = 1 [(required) = true];
  // Provides the registered SKU name.
  string display_name = 2 [(required) = true];
}
