syntax = "proto3";

package spine.examples.todo;

import "spine/examples/todo/task_id.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.todo";

// Rejects completion of a task that is already completed.
message TaskAlreadyDone {
  // Identifies the already completed task.
  TaskId id = 1 [
    (required) = true,
    (validate) = true
  ];
}

// Rejects reopening a task that is not completed.
message TaskNotDone {
  // Identifies the task that is not completed.
  TaskId id = 1 [
    (required) = true,
    (validate) = true
  ];
}
