/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
syntax = "proto3";

package spine.examples.todo;

import "spine/examples/todo/tasks.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.todo";

// A list of tasks with its count of open tasks.
message TaskList {
  option (entity).kind = PROJECTION;
  option (entity).visibility = FULL;

  // Identifies this task list.
  string id = 1 [
    (required) = true,
    (set_once) = true
  ];

  // The tasks in this list.
  repeated Task tasks = 2 [(validate) = true];

  // Counts tasks that are not completed.
  int32 open_task_count = 3 [(column) = true];
}
