import { getOption, hasOption } from "@bufbuild/protobuf";
import type { DescField, DescFile, Message } from "@bufbuild/protobuf";
import type { GenMessage } from "@bufbuild/protobuf/codegenv2";
import {
  column,
  entity,
  type EntityOption,
  EntityOption_Kind,
  EntityOption_Visibility,
  every_is,
  is,
  set_once,
} from "@spine-ts/proto";

/** Protobuf-ES message schema accepted by the server descriptor metadata APIs. */
export type DescriptorMessageSchema = GenMessage<Message>;

/** Normalized Spine entity kind derived from `(entity).kind`. */
export type EntityKind = "aggregate" | "projection" | "process-manager" | "entity";

/** Normalized Spine entity visibility after default application. */
export type EntityVisibility = "none" | "subscribe" | "query" | "full";

/** Visibility declared directly in `(entity).visibility`, before defaulting. */
export type DeclaredEntityVisibility = EntityVisibility | "default";

/** Machine-readable codes for descriptor metadata extraction failures. */
export type DescriptorMetadataErrorCode =
  | "NOT_ENTITY_SCHEMA"
  | "UNSUPPORTED_ENTITY_KIND"
  | "UNSUPPORTED_ENTITY_VISIBILITY"
  | "MISSING_ENTITY_ID_FIELD"
  | "INVALID_COLUMN_FIELD"
  | "INVALID_SEMANTIC_TAG";

/** Descriptor-derived metadata for one Protobuf field. */
export interface DescriptorFieldMetadata<Field extends DescField = DescField> {
  /** Descriptor identity for the field. */
  readonly descriptor: Field;
  /** Protobuf field name as declared in source. */
  readonly name: Field["name"];
  /** ECMAScript-safe property name generated by Protobuf-ES. */
  readonly localName: Field["localName"];
  /** JSON field name. */
  readonly jsonName: Field["jsonName"];
  /** Protobuf field number. */
  readonly number: Field["number"];
}

/** Hint for later default command/event routing by the first declared field. */
export interface FirstFieldRoutingHint<Field extends DescField = DescField> {
  /** Current default routing strategy preserved from Spine descriptor order. */
  readonly strategy: "first-field";
  /** Field that later routing logic should inspect. */
  readonly field: DescriptorFieldMetadata<Field>;
}

/** Descriptor-derived entity metadata used by later runtime registration tasks. */
export interface EntityMetadata<Schema extends DescriptorMessageSchema = DescriptorMessageSchema> {
  /** Generated Protobuf-ES schema describing the entity state message. */
  readonly schema: Schema;
  /** Alias for the schema as the descriptor-bearing message declaration. */
  readonly descriptor: Schema;
  /** Fully qualified Protobuf type name. */
  readonly fullTypeName: Schema["typeName"];
  /** Declaring file descriptor. */
  readonly fileDescriptor: DescFile;
  /** Declaring file name with `.proto` restored. */
  readonly fileName: string;
  /** Normalized entity kind. */
  readonly kind: EntityKind;
  /** Visibility directly declared in `(entity).visibility`. */
  readonly declaredVisibility: DeclaredEntityVisibility;
  /** Effective visibility after Spine defaults are applied. */
  readonly visibility: EntityVisibility;
  /** Whether visibility came from an explicit option or a kind default. */
  readonly visibilitySource: "default" | "explicit";
  /** Canonical entity ID field, taken from the first declared field. */
  readonly idField: DescriptorFieldMetadata;
  /** Descriptor hint for later first-field routing. */
  readonly firstFieldRoutingHint: FirstFieldRoutingHint;
  /**
   * Fields marked `(column) = true`, in descriptor declaration order, for
   * column-eligible entity kinds only. Aggregate and generic entity column
   * declarations are ignored in this slice.
   */
  readonly columns: readonly DescriptorFieldMetadata[];
  /** Fields marked `(set_once) = true`, in descriptor declaration order. */
  readonly setOnceFields: readonly DescriptorFieldMetadata[];
  /** Semantic tags from `(is)` and `(every_is)`, deduplicated and sorted. */
  readonly semanticTags: readonly string[];
}

/** Error thrown when descriptor metadata cannot be derived for a schema. */
export class DescriptorMetadataError extends Error {
  /** Stable code for callers/tests that need structured failure handling. */
  readonly code: DescriptorMetadataErrorCode;

  constructor(code: DescriptorMetadataErrorCode, message: string) {
    super(message);
    this.name = "DescriptorMetadataError";
    this.code = code;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

/** Return whether the schema declares Spine `(entity)` metadata. */
export function isEntitySchema(schema: DescriptorMessageSchema): boolean {
  return hasOption(schema, entity);
}

/** Derive deterministic entity metadata from a Protobuf-ES schema descriptor. */
export function describeEntityMetadata<Schema extends DescriptorMessageSchema>(
  schema: Schema,
): EntityMetadata<Schema> {
  if (!isEntitySchema(schema)) {
    throw new DescriptorMetadataError(
      "NOT_ENTITY_SCHEMA",
      `Schema "${schema.typeName}" requires an (entity) option before entity metadata can be derived.`,
    );
  }

  const entityOption = getOption(schema, entity);
  const kind = normalizeEntityKind(schema, entityOption.kind);
  const declaredVisibility = normalizeDeclaredVisibility(schema, entityOption.visibility);
  const visibility = resolveVisibility(kind, declaredVisibility);
  const idFieldDescriptor = schema.fields[0];

  if (idFieldDescriptor === undefined) {
    throw new DescriptorMetadataError(
      "MISSING_ENTITY_ID_FIELD",
      `Entity schema "${schema.typeName}" must declare at least one field for its ID and routing metadata.`,
    );
  }

  const idField = createFieldMetadata(idFieldDescriptor);
  const firstFieldRoutingHint: FirstFieldRoutingHint = Object.freeze({
    strategy: "first-field",
    field: idField,
  });
  const columns = collectColumns(schema, kind);
  const setOnceFields = Object.freeze(
    schema.fields
      .filter((field) => hasOption(field, set_once) && getOption(field, set_once))
      .map(createFieldMetadata),
  );
  const semanticTags = collectSemanticTags(schema);
  const metadata: EntityMetadata<Schema> = {
    schema,
    descriptor: schema,
    fullTypeName: schema.typeName,
    fileDescriptor: schema.file,
    fileName: `${schema.file.name}.proto`,
    kind,
    declaredVisibility,
    visibility,
    visibilitySource: declaredVisibility === "default" ? "default" : "explicit",
    idField,
    firstFieldRoutingHint,
    columns,
    setOnceFields,
    semanticTags,
  };

  return Object.freeze(metadata);
}

function createFieldMetadata<Field extends DescField>(
  field: Field,
): DescriptorFieldMetadata<Field> {
  return Object.freeze({
    descriptor: field,
    name: field.name,
    localName: field.localName,
    jsonName: field.jsonName,
    number: field.number,
  });
}

function normalizeEntityKind(
  schema: DescriptorMessageSchema,
  value: EntityOption["kind"],
): EntityKind {
  switch (value) {
    case EntityOption_Kind.AGGREGATE:
      return "aggregate";
    case EntityOption_Kind.PROJECTION:
      return "projection";
    case EntityOption_Kind.PROCESS_MANAGER:
      return "process-manager";
    case EntityOption_Kind.ENTITY:
      return "entity";
    case EntityOption_Kind.KIND_UNKNOWN:
    default:
      throw new DescriptorMetadataError(
        "UNSUPPORTED_ENTITY_KIND",
        `Schema "${schema.typeName}" declares unsupported entity kind "${formatEntityKind(value)}".`,
      );
  }
}

function normalizeDeclaredVisibility(
  schema: DescriptorMessageSchema,
  value: EntityOption["visibility"],
): DeclaredEntityVisibility {
  switch (value) {
    case EntityOption_Visibility.DEFAULT:
      return "default";
    case EntityOption_Visibility.NONE:
      return "none";
    case EntityOption_Visibility.SUBSCRIBE:
      return "subscribe";
    case EntityOption_Visibility.QUERY:
      return "query";
    case EntityOption_Visibility.FULL:
      return "full";
    default:
      throw new DescriptorMetadataError(
        "UNSUPPORTED_ENTITY_VISIBILITY",
        `Schema "${schema.typeName}" declares unsupported entity visibility "${String(value)}".`,
      );
  }
}

function resolveVisibility(kind: EntityKind, declared: DeclaredEntityVisibility): EntityVisibility {
  if (declared !== "default") {
    return declared;
  }

  return kind === "projection" ? "full" : "none";
}

function collectColumns(
  schema: DescriptorMessageSchema,
  kind: EntityKind,
): readonly DescriptorFieldMetadata[] {
  if (!supportsColumns(kind)) {
    return Object.freeze([]);
  }

  return Object.freeze(
    schema.fields
      .filter((field) => hasOption(field, column) && getOption(field, column))
      .map((field) => {
        validateColumnField(schema, field);
        return createFieldMetadata(field);
      }),
  );
}

function supportsColumns(kind: EntityKind): boolean {
  return kind === "projection" || kind === "process-manager";
}

function validateColumnField(schema: DescriptorMessageSchema, field: DescField): void {
  if (field.fieldKind === "list" || field.fieldKind === "map") {
    throw new DescriptorMetadataError(
      "INVALID_COLUMN_FIELD",
      `Entity column field "${schema.typeName}.${field.name}" must be singular; ` +
        "repeated and map fields are unsupported.",
    );
  }
}

function collectSemanticTags(schema: DescriptorMessageSchema): readonly string[] {
  const tags = new Set<string>();

  if (hasOption(schema.file, every_is)) {
    tags.add(readSemanticTag(getOption(schema.file, every_is).javaType, schema.file.name));
  }

  if (hasOption(schema, is)) {
    tags.add(readSemanticTag(getOption(schema, is).javaType, schema.typeName));
  }

  return Object.freeze([...tags].sort());
}

function readSemanticTag(rawValue: string, owner: string): string {
  const value = rawValue.trim();

  if (value.length === 0) {
    throw new DescriptorMetadataError(
      "INVALID_SEMANTIC_TAG",
      `Entity semantic tag option "${owner}" must declare a non-empty java_type.`,
    );
  }

  return value;
}

function formatEntityKind(value: number): string {
  return EntityOption_Kind[value] ?? String(value);
}
