packages:
  - "packages/*"
  - "examples/*"
confirmModulesPurge: false
engineStrict: true
enableGlobalVirtualStore: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - js-yaml@4.3.0
  - prettier@3.9.0
verifyDepsBeforeRun: error
onlyBuiltDependencies:
  - "@bufbuild/buf"
  - zeromq
allowBuilds:
  "@bufbuild/buf": true
  protobufjs: set this to true or false
  zeromq: true
