syntax = "proto3";

package spine.example.todo.v1;

import "spine/example/todo/v1/tasks.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.example.todo";

// Projects tasks into a list with its count of open tasks.
message TaskList {
  option (entity).kind = PROJECTION;
  option (entity).visibility = FULL;

  // Identifies this task-list projection.
  string id = 1 [
    (required) = true,
    (set_once) = true
  ];
  // Contains the tasks in this projection.
  repeated Task tasks = 2 [(validate) = true];
  // Counts tasks that are not completed.
  int32 open_task_count = 3 [(column) = true];
}
