syntax = "proto3";
package spine.examples.chat;

import "google/protobuf/timestamp.proto";
import "spine/examples/chat/users.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.chat";

// Identifies the Chat room that contains messages.
message ChatRoomId {

  // Contains the room's Chat identifier.
  string value = 1 [(required) = true];
}

// Identifies a message in a Chat room.
message MessageId {

  // Contains the message's Chat identifier.
  string value = 1 [(required) = true];
}

// Holds saved data for a Chat message.
message ChatMessage {
  option (entity).kind = AGGREGATE;

  // Identifies this Chat message.
  MessageId id = 1 [(required) = true, (validate) = true, (set_once) = true];

  // Identifies the room that contains this message.
  ChatRoomId room = 2 [(required) = true, (validate) = true];

  // Identifies the Chat user who posted this message.
  UserId author = 3 [(required) = true, (validate) = true];

  // Contains the text written in this message.
  string text = 4 [(required) = true];

  // Records when the message was posted.
  google.protobuf.Timestamp posted_at = 5 [(required) = true];
}

// Describes a Chat message shown in a room.
message ChatMessageView {
  option (entity).kind = PROJECTION;
  option (entity).visibility = FULL;

  // Identifies this Chat message.
  MessageId id = 1 [(required) = true, (validate) = true, (set_once) = true];

  // Identifies the room that contains this message.
  ChatRoomId room = 2 [(required) = true, (validate) = true, (column) = true];

  // Identifies the Chat user who posted this message.
  UserId author = 3 [(required) = true, (validate) = true, (column) = true];

  // Contains the text written in this message.
  string text = 4 [(required) = true];

  // Records when this message was posted.
  google.protobuf.Timestamp posted_at = 5 [(required) = true, (column) = true];
}
