syntax = "proto3";
package spine.examples.chat;

import "google/protobuf/timestamp.proto";
import "spine/examples/chat/chat.proto";
import "spine/examples/chat/users.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.chat";

// Records a message posted to a Chat room.
message MessagePosted {

  // Identifies the message that was posted.
  MessageId id = 1 [(required) = true, (validate) = true];

  // Identifies the room that received the message.
  ChatRoomId room = 2 [(required) = true, (validate) = true];

  // Identifies the Chat user who posted the message.
  UserId author = 3 [(required) = true, (validate) = true];

  // Contains the text of the posted message.
  string text = 4 [(required) = true];

  // Records when the message was posted.
  google.protobuf.Timestamp posted_at = 5 [(required) = true];
}
