syntax = "proto3";
package spine.example.chat.v1;

import "google/protobuf/timestamp.proto";
import "spine/example/chat/v1/chat.proto";
import "spine/example/users/v1/users.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.example.chat";

// Posts a message to a chat room.
message PostMessage {
  // Identifies the message to post to the room.
  MessageId id = 1 [(required) = true, (validate) = true];
  // Identifies the room that receives the message.
  ChatRoomId room = 2 [(required) = true, (validate) = true];
  // Identifies the user who posts the message.
  spine.example.users.v1.UserId author = 3 [(required) = true, (validate) = true];
  // Provides the text of the new message.
  string text = 4 [(required) = true];
  // Specifies when the user posted the message.
  google.protobuf.Timestamp posted_at = 5 [(required) = true];
}
