syntax = "proto3";
package spine.example.chat.v1;

import "google/protobuf/timestamp.proto";
import "spine/example/chat/v1/chat.proto";
import "spine/example/users/v1/users.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.example.chat";

// Records a message posted to a chat room.
message MessagePosted {
  // Identifies the message that was posted.
  MessageId id = 1 [(required) = true, (validate) = true];
  // Identifies the room that received the message.
  ChatRoomId room = 2 [(required) = true, (validate) = true];
  // Identifies the user who posted the message.
  spine.example.users.v1.UserId author = 3 [(required) = true, (validate) = true];
  // Contains the text of the posted message.
  string text = 4 [(required) = true];
  // Records when the message was posted.
  google.protobuf.Timestamp posted_at = 5 [(required) = true];
}
