/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

/**
 * Contains the exact local descriptor for the Process Manager fixture's entity metadata.
 */
export const processManagerDescriptorBase64 =
  "CroKCiBlbnRpdHktbWV0YWRhdGEvdmlzaWJpbGl0eS5wcm90bxoTc3BpbmUvb3B0aW9ucy5wcm90byJLChNQcm9jZXNzTWFuYWdlclN0YXRlEg4KAmlkGAEgASgJUgJpZBIaCgVxdWV1ZRgCIAEoCUIE8IckAVIFcXVldWU6CPqKJAQIAxACIi8KE0Z1bGxWaXNpYmlsaXR5U3RhdGUSDgoCaWQYASABKAlSAmlkOgj6iiQECAQQBCInCgtIaWRkZW5TdGF0ZRIOCgJpZBgBIAEoCVICaWQ6CPqKJAQIBBABStEICgYSBA0AJQEK0AQKAQwSAw0AEhrFBAogQ29weXJpZ2h0IDIwMjYsIENvZGVNYXR0ZXJzLiBBbGwgcmlnaHRzIHJlc2VydmVkLgoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOyB5b3UgbWF5IG5vdCB1c2UgdGhpcyBmaWxlIGV4Y2VwdAogaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLiBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKCiBodHRwczovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCgogVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZSBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZQogaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzCiBvciBpbXBsaWVkLiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kIGxpbWl0YXRpb25zIHVuZGVyCiB0aGUgTGljZW5zZS4KCgkKAgMAEgMPAB0KCgoCBAASBBEAFwEKCgoDBAABEgMRCBsKCgoDBAAHEgMSAikKDgoHBAAHr8EEARIDEgIpCgoKAwQABxIDEwIpCg4KBwQAB6/BBAISAxMCKQoMCgUEAAIABRIDFQIICgsKBAQAAgASAxUCEAoMCgUEAAIAARIDFQkLCgwKBQQAAgADEgMVDg8KDAoFBAACAQUSAxYCCAoLCgQEAAIBEgMWAiUKDAoFBAACAQESAxYJDgoMCgUEAAIBAxIDFhESCgwKBQQAAgEIEgMWEyQKDwoIBAACAQj+wAQSAxYUIwoKCgIEARIEGQAeAQoKCgMEAQESAxkIGwoKCgMEAQcSAxoCIAoOCgcEAQevwQQBEgMaAiAKCgoDBAEHEgMbAiQKDgoHBAEHr8EEAhIDGwIkCgwKBQQBAgAFEgMdAggKCwoEBAECABIDHQIQCgwKBQQBAgABEgMdCQsKDAoFBAECAAMSAx0ODwoKCgIEAhIEIAAlAQoKCgMEAgESAyAIEwoKCgMEAgcSAyECIAoOCgcEAgevwQQBEgMhAiAKCgoDBAIHEgMiAiQKDgoHBAIHr8EEAhIDIgIkCgwKBQQCAgAFEgMkAggKCwoEBAICABIDJAIQCgwKBQQCAgABEgMkCQsKDAoFBAICAAMSAyQOD2IGcHJvdG8z";
