import type { AuthenticatedPrincipal, RequestCredential, ResolvedSession } from "../index.js";

/** Clock used to evaluate finite OIDC transactions. */
export interface OidcFlowClock {
  /** Returns a safe Unix epoch millisecond value in the Protobuf Timestamp range.
   * @returns The current milliseconds.
   */
  now(): number;
}

/** Creates random OIDC state, nonce, and PKCE verifier material.
 * @param length The required byte length.
 * @returns The generated bytes.
 */
export type OidcFlowRandom = (length: number) => Uint8Array;

/** A provider identity verified against its authorization-code response. */
export interface ExternalIdentity {
  /** Identifies the verified provider issuer. */
  readonly issuer: string;
  /** Identifies the provider subject. */
  readonly subject: string;
  /** Provides verified provider claims. */
  readonly claims?: Readonly<Record<string, string>>;
}

/** Application identity produced by a provider-neutral mapping. */
export interface ResolvedApplicationIdentity {
  /** Provides the verified provider identity. */
  readonly externalIdentity: ExternalIdentity;
  /** Provides the mapped application principal. */
  readonly principal: AuthenticatedPrincipal;
}

/** Application-owned mapping from a verified external identity to a principal. */
export interface IdentityMapping {
  /** Resolves a verified identity to an application principal.
   * @param identity The verified provider identity.
   * @param signal The operation cancellation signal.
   * @returns The mapped identity, or undefined when it is not admitted.
   */
  resolve(
    identity: ExternalIdentity,
    signal: AbortSignal,
  ): Promise<ResolvedApplicationIdentity | undefined>;
}

/** Input to an adapter that exchanges and verifies an authorization code. */
export interface OidcAuthorizationCodeExchange {
  /** Provides the provider authorization code. */
  readonly code: string;
  /** Provides the configured OAuth client ID. */
  readonly clientId: string;
  /** Provides the configured callback URI. */
  readonly callbackUri: string;
  /** Provides the provider PKCE verifier. */
  readonly providerCodeVerifier: string;
  /** Provides the nonce expected in the ID token. */
  readonly expectedNonce: string;
  /** Cancels the provider exchange. */
  readonly signal: AbortSignal;
}

/** Provider-specific authorization-code and identity-verification seam. */
export interface OidcVerifiedIdentityProvider {
  /** Identifies the provider issuer. */
  readonly issuer: string;
  /** Processes and verifies a provider authorization code.
   * @param input The provider exchange input.
   * @returns The verified identity, or undefined when verification fails.
   */
  exchangeAuthorizationCode(
    input: OidcAuthorizationCodeExchange,
  ): Promise<ExternalIdentity | undefined>;
}

/** Result issued by the application-selected application-session strategy. */
export interface ApplicationSessionIssue {
  /** Provides the issued application credential. */
  readonly credential: RequestCredential;
  /** Provides the issued application session. */
  readonly session: ResolvedSession;
}

/** Application-session seam used only after a successful OIDC grant exchange. */
export interface ApplicationSessionIssuer {
  /** Creates an application session for a mapped principal.
   * @param principal The mapped principal.
   * @param signal The operation cancellation signal.
   * @returns The issued session, or undefined when issuance fails.
   */
  issue(
    principal: AuthenticatedPrincipal,
    signal: AbortSignal,
  ): Promise<ApplicationSessionIssue | undefined>;
}

/** Construction options for the bounded, framework-neutral OIDC code flow. */
export interface OidcFlowOptions {
  /** Provides the trusted authorization endpoint. */
  readonly authorizationEndpoint: string;
  /** Provides the application callback URI. */
  readonly callbackUri: string;
  /** Provides the OAuth client ID. */
  readonly clientId: string;
  /** Provides requested provider scopes. */
  readonly scopes: readonly string[];
  /** Provides permitted post-login redirects. */
  readonly allowedPostLoginRedirects: readonly string[];
  /** Provides the verified identity provider. */
  readonly provider: OidcVerifiedIdentityProvider;
  /** Maps verified identities to principals. */
  readonly identityMapping: IdentityMapping;
  /** Issues application sessions. */
  readonly sessionIssuer: ApplicationSessionIssuer;
  /** Provides the optional flow clock. */
  readonly clock?: OidcFlowClock;
  /** Provides the optional random-byte source. */
  readonly randomBytes?: OidcFlowRandom;
  /** Limits transaction lifetime in milliseconds. */
  readonly transactionTtlMilliseconds?: number;
  /** Limits grant lifetime in milliseconds. */
  readonly grantTtlMilliseconds?: number;
  /** Limits retained transactions. */
  readonly maxTransactions?: number;
  /** Limits retained grants. */
  readonly maxGrants?: number;
  /** Limits entropy collision retries. */
  readonly collisionAttempts?: number;
  /** Limits provider-operation time in milliseconds. */
  readonly operationTimeoutMilliseconds?: number;
  /** Limits authorization URL length. */
  readonly maxAuthorizationUrlLength?: number;
}

/** Input accepted by {@link OidcFlow.start}. */
export interface OidcFlowStartInput {
  /** Browser-generated RFC 7636 S256 code challenge. */
  readonly browserCodeChallenge: string;
  /** Exact preconfigured application redirect to use after successful sign-in. */
  readonly postLoginRedirect: string;
}

/** Result of opening one authorization-code transaction. */
export type OidcFlowStartResult =
  | {
      /** Identifies a started transaction. */ readonly kind: "started";
      /** Provides the authorization URL. */ readonly authorizationUrl: string;
      /** Provides transaction expiry milliseconds. */ readonly expiresAt: number;
    }
  | {
      /** Identifies a rejected transaction. */
      readonly kind: "rejected";
      /** Explains why the transaction was rejected. */
      readonly reason:
        "invalid-input" | "capacity-exceeded" | "entropy-exhausted" | "clock-failure" | "closed";
    };

/** Common callback facts. Exactly one of code or error is required. */
export interface OidcFlowCallbackBase {
  /** Provides the one-time callback state. */
  readonly state: string;
  /** Optional issuer returned by a provider authorization response. */
  readonly responseIssuer?: string;
}
/** Input accepted by {@link OidcFlow.callback}. */
export type OidcFlowCallbackInput =
  | (OidcFlowCallbackBase & {
      /** Provides the provider code. */ readonly code: string;
      /** Excludes provider error. */ readonly error?: never;
    })
  | (OidcFlowCallbackBase & {
      /** Provides the provider error. */ readonly error: string;
      /** Excludes provider code. */ readonly code?: never;
    });

/** Result of atomically consuming an authorization-code transaction. */
export type OidcFlowCallbackResult =
  | {
      /** Identifies an accepted callback. */
      readonly kind: "granted";
      /** Provides the one-time application grant. */
      readonly grant: string;
      /** Provides the permitted post-login redirect. */
      readonly postLoginRedirect: string;
      /** Provides grant expiry milliseconds. */
      readonly expiresAt: number;
    }
  | {
      /** Identifies a rejected callback. */
      readonly kind: "rejected";
      /** Explains why the callback was rejected. */
      readonly reason:
        | "invalid-input"
        | "not-found"
        | "expired"
        | "provider-error"
        | "issuer-mismatch"
        | "verification-failed"
        | "mapping-failed"
        | "capacity-exceeded"
        | "entropy-exhausted"
        | "clock-failure"
        | "closed";
    };

/** Input accepted by {@link OidcFlow.exchange}. */
export interface OidcFlowExchangeInput {
  /** One-time grant returned by {@link OidcFlow.callback}. */
  readonly grant: string;
  /** Browser-held RFC 7636 verifier for the application's separate grant. */
  readonly browserCodeVerifier: string;
}

/** Enumeration-safe result of a one-time application-session exchange. */
export type OidcFlowExchangeResult =
  | {
      /** Identifies an issued application session. */
      readonly kind: "issued";
      /** Provides the issued application credential. */
      readonly credential: RequestCredential;
      /** Provides the issued application session. */
      readonly session: ResolvedSession;
    }
  | {
      /** Identifies a rejected exchange. */
      readonly kind: "rejected";
    };
