syntax = "proto3";

package spine.examples.orders;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.orders";

// An order placed for one SKU.
message Order {
  option (entity).kind = AGGREGATE;

  // Uniquely identifies a placed order.
  string id = 1 [(required) = true, (set_once) = true];

  // The SKU in the order.
  string sku_id = 2 [(required) = true];
}

// A SKU available for ordering.
message Sku {
  option (entity).kind = AGGREGATE;

  // Uniquely identifies an available SKU.
  string id = 1 [(required) = true, (set_once) = true];

  // A name shown for the SKU.
  string display_name = 2 [(required) = true];
}
