syntax = "proto3";
package spine.example.project_management.v1;
import "spine/options.proto";
option (type_url_prefix) = "type.spine.example.project-management";
// Represents a project aggregate.
message Project {
  option (entity).kind = AGGREGATE;
  // Carries the project identifier.
  string id = 1 [(required) = true, (set_once) = true];
  // Carries the project's display name.
  string name = 2 [(required) = true];
}
// Represents a task aggregate.
message Task {
  option (entity).kind = AGGREGATE;
  // Carries the task identifier.
  string id = 1 [(required) = true, (set_once) = true];
  // References the task's project.
  string project_id = 2 [(required) = true];
}
// Represents a person aggregate.
message Person {
  option (entity).kind = AGGREGATE;
  // Carries the person's identifier.
  string id = 1 [(required) = true, (set_once) = true];
  // Carries the person's display name.
  string display_name = 2 [(required) = true];
}
