/* Shared publishable generated-TypeScript provenance policy. */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

export function generatedNotice(sources: readonly string[]): string {
  const paths = [...new Set(sources)].sort();
  if (paths.length === 0 || !paths.every(stableProtoPath))
    throw new Error("spine-proto: generated source requires stable Proto provenance");
  return ["/*", " * Generated by Spine TypeScript. Do not edit manually.", ...paths.map((path) => ` * Source Proto: ${path}`), " */", "", ""].join("\n");
}

export function generatedSource(source: string, sources: readonly string[]): string {
  const body = source.replace(/^\/\*[\s\S]*?CodeMatters[\s\S]*? \*\/\n*/u, "");
  return `${generatedNotice(sources)}${body.replace(/(^|\n)(export (?:const|interface|enum|type|class|function) )/gu, (_match, prefix, declaration) => `${prefix}/**\n * Generated from Proto: ${[...new Set(sources)].sort().join(", ")}.\n */\n${declaration}`)}`;
}

export function normalizeGeneratedTree(root: string, sources: readonly string[]): void {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) normalizeGeneratedTree(path, sources);
    else if (entry.isFile() && path.endsWith(".ts")) writeFileSync(path, generatedSource(readFileSync(path, "utf8"), sources), "utf8");
  }
}

function stableProtoPath(path: string): boolean {
  return typeof path === "string" && /^[A-Za-z0-9][A-Za-z0-9._/-]*\.proto$/u.test(path) && !path.includes("..") && !path.includes("\\") && !/(?:stage|backup|temp|tmp)/iu.test(path);
}
