/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

/* Shared publishable generated-TypeScript provenance policy. */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

/**
 * Renders a deterministic generated-file notice.
 * @param sources Stable source Proto import paths.
 * @returns The generated-file notice.
 */
export function generatedNotice(sources: readonly string[]): string {
  const paths = [...new Set(sources)].sort();
  if (paths.length === 0 || !paths.every(stableProtoPath))
    throw new Error(
      `spine-proto: generated source requires stable Proto provenance ${JSON.stringify(paths)}`,
    );
  return [
    "/*",
    " * Generated by Spine TypeScript. Do not edit manually.",
    ...paths.map((path) => ` * Source Proto: ${path}`),
    " */",
    "",
    "",
  ].join("\n");
}

/**
 * Applies generated provenance to TypeScript source.
 * @param source Generated TypeScript source.
 * @param sources Stable source Proto import paths.
 * @returns Source with generated provenance.
 */
export function generatedSource(source: string, sources: readonly string[]): string {
  const body = source.replace(/^\/\*[\s\S]*?CodeMatters[\s\S]*? \*\/\n*/u, "");
  return `${generatedNotice(sources)}${body.replace(/(^|\n)(export (?:const|interface|enum|type|class|function) )/gu, (_match, prefix, declaration) => `${prefix}/**\n * Generated from Proto: ${[...new Set(sources)].sort().join(", ")}.\n */\n${declaration}`)}`;
}

/**
 * Normalizes generated TypeScript files below a directory.
 * @param root Generated output directory.
 * @param sources Authoritative fallback Proto import paths.
 */
export function normalizeGeneratedTree(root: string, sources: readonly string[]): void {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) normalizeGeneratedTree(path, sources);
    else if (
      entry.isFile() &&
      /(?:_pb|rejections|_columns|proto-module|generated-handler-registry)\.ts$/u.test(path)
    ) {
      const source = readFileSync(path, "utf8");
      const derived = [...source.matchAll(/from "(?:[^" ]+\/generated\/)?([^" ]+)_pb\.js"/gu)].map(
        (match) =>
          (match[1] ?? "").replace(/^\.\//u, "").replace(/^.*?spine\//u, "spine/") + ".proto",
      );
      const generated = [...source.matchAll(/@generated from file ([^\s)]+)/gu)].map(
        (match) => match[1] ?? "",
      );
      const provenance = derived.length > 0 ? derived : generated.length > 0 ? generated : sources;
      if (provenance.length > 0) writeFileSync(path, generatedSource(source, provenance), "utf8");
    }
  }
}

function stableProtoPath(path: string): boolean {
  return (
    typeof path === "string" &&
    path.length > 0 &&
    path.endsWith(".proto") &&
    !path.startsWith("/") &&
    !/^[A-Za-z]:/u.test(path) &&
    !path.split("/").some((part) => part === "" || part === "." || part === "..") &&
    !path.includes("\\") &&
    !/(?:stage|backup|temp|tmp)/iu.test(path)
  );
}
