/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

/* Shared publishable generated-TypeScript provenance policy. */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Renders a deterministic generated-file notice.
 * @param sources Stable source Proto import paths.
 * @returns The generated-file notice.
 */
const generatedPolicy = Object.freeze({
  generatedNotice(sources: readonly string[]): string {
    const paths = [...new Set(sources)].sort();
    if (paths.length === 0 || !paths.every(generatedPolicy.stableProtoPath))
      throw new Error(
        `spine-proto: generated source requires stable Proto provenance ${JSON.stringify(paths)}`,
      );
    return [
      "/*",
      " * Generated by Spine TypeScript. Do not edit manually.",
      ...paths.map((path) => ` * Source Proto: ${path}`),
      " */",
      "",
      "",
    ].join("\n");
  },

  /* Applies generated provenance to TypeScript source. */
  generatedSource(source: string, sources: readonly string[]): string {
    let copiedPreamble = source.replace(
      /^\/\*\n \* Generated by Spine TypeScript\. Do not edit manually\.\n(?: \* Source Proto: .*\n)+ \*\/\n*/u,
      "",
    );
    const leadingBlock = /^\/\*[\s\S]*?\*\/\s*/u.exec(copiedPreamble)?.[0];
    if (
      leadingBlock !== undefined &&
      /copyright|licen[cs](?:ed|e)|proprietary|confidential/iu.test(leadingBlock)
    )
      copiedPreamble = copiedPreamble.slice(leadingBlock.length);
    const leadingLines = /^(?:(?:\/\/[^\n]*\n)+)/u.exec(copiedPreamble)?.[0];
    if (
      leadingLines !== undefined &&
      /copyright|licen[cs](?:ed|e)|proprietary|confidential/iu.test(leadingLines)
    )
      copiedPreamble = `${leadingLines
        .split("\n")
        .filter((line) => line.startsWith("// @generated"))
        .join("\n")}\n${copiedPreamble.slice(leadingLines.length)}`;
    const withoutCopyright = copiedPreamble;
    const lines = withoutCopyright.split("\n");
    const generatedAt = lines.findIndex((line) => line.startsWith("// @generated"));
    const body =
      generatedAt !== -1 && lines.slice(0, generatedAt).some((line) => line.includes("CodeMatters"))
        ? lines.slice(generatedAt).join("\n")
        : withoutCopyright;
    const provenance = ` * Generated from Proto: ${[...new Set(sources)].sort().join(", ")}.`;
    return `${generatedPolicy.generatedNotice(sources)}${body.replace(
      /(^|\n)(\/\*\*[\s\S]*?\*\/\n)?(export (?:declare )?(?:const|interface|enum|type|class|function) )/gu,
      (_match: string, prefix: string, documentation: string | undefined, declaration: string) => {
        const cleaned = (documentation ?? "").replace(/ \* Generated from Proto: .*\.\n/gu, "");
        const oneLine = /^\/\*\*[ \t]*([^\n]*?)[ \t]*\*\/\n$/u.exec(cleaned);
        const normalized = oneLine === null ? cleaned : `/**\n * ${oneLine[1] ?? ""}\n */\n`;
        return cleaned === ""
          ? `${prefix}/**\n${provenance}\n */\n${declaration}`
          : `${prefix}${normalized.replace(/ \*\/\n$/u, `${provenance}\n */\n`)}${declaration}`;
      },
    )}`;
  },

  /* Normalizes generated TypeScript files below a directory. */
  normalizeGeneratedTree(root: string, sources: readonly string[]): void {
    generatedPolicy.normalizeGeneratedTreeAt(root, sources, 0, { entries: 0 });
  },

  normalizeGeneratedTreeAt(
    root: string,
    sources: readonly string[],
    depth: number,
    state: { entries: number },
  ): void {
    if (depth > 64 || state.entries > 1_000)
      throw new Error("spine-proto: generated source traversal exceeds bounded inventory");
    for (const entry of readdirSync(root, { withFileTypes: true })) {
      state.entries += 1;
      if (state.entries > 1_000)
        throw new Error("spine-proto: generated source traversal exceeds bounded inventory");
      const path = join(root, entry.name);
      if (entry.isDirectory())
        generatedPolicy.normalizeGeneratedTreeAt(path, sources, depth + 1, state);
      else if (
        entry.isFile() &&
        /(?:_pb|rejections|_columns|proto-module|generated-handler-registry)\.ts$/u.test(path)
      ) {
        const source = readFileSync(path, "utf8");
        const derived = [
          ...source.matchAll(/from "(?:[^" ]+\/generated\/)?([^" ]+)_pb\.js"/gu),
        ].map(
          (match) =>
            (match[1] ?? "").replace(/^\.\//u, "").replace(/^.*?spine\//u, "spine/") + ".proto",
        );
        const generated = [...source.matchAll(/@generated from file ([^\s)]+)/gu)].map(
          (match) => match[1] ?? "",
        );
        const provenance =
          generated.length > 0 ? generated : derived.length > 0 ? derived : sources;
        if (provenance.length > 0)
          writeFileSync(path, generatedPolicy.generatedSource(source, provenance), "utf8");
      }
    }
  },

  stableProtoPath(path: string): boolean {
    const components = path.split("/");
    return (
      typeof path === "string" &&
      path.length > 0 &&
      path.endsWith(".proto") &&
      !path.startsWith("/") &&
      !/^[A-Za-z]:/u.test(path) &&
      !components.some((part) => part === "" || part === "." || part === "..") &&
      !path.includes("\\") &&
      !components.some(
        (part) =>
          part === "tmp" || part === "temp" || /^\.(?:generated|stage|backup)(?:-|$)/u.test(part),
      )
    );
  },
});

/**
 * Renders a deterministic generated-file notice.
 */
export const generatedNotice: (sources: readonly string[]) => string =
  generatedPolicy.generatedNotice;

/**
 * Renders the deterministic generated-file notice for script consumers.
 */
export const generatedFileNotice: (sources: readonly string[]) => string = generatedNotice;

/**
 * Applies generated provenance to TypeScript source.
 */
export const generatedSource: (source: string, sources: readonly string[]) => string =
  generatedPolicy.generatedSource;

/**
 * Applies generated provenance using the script-compatible name.
 */
export const generatedTypeScript: (source: string, sources: readonly string[]) => string =
  generatedSource;

/**
 * Normalizes generated TypeScript files below a directory.
 */
export const normalizeGeneratedTree: (root: string, sources: readonly string[]) => void =
  generatedPolicy.normalizeGeneratedTree;
