/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
syntax = "proto3";
package spine.examples.messageboard;

import "google/protobuf/timestamp.proto";
import "spine/examples/messageboard/message_board.proto";
import "spine/examples/messageboard/user.proto";
import "spine/options.proto";

option (type_url_prefix) = "type.spine.examples.messageboard";

// Records a message posted on a board.
message MessagePosted {

  // The identifier assigned to the posted message.
  MessageId id = 1 [(required) = true, (validate) = true];

  // The board that received the message.
  BoardId board = 2 [(required) = true, (validate) = true];

  // The account that posted the message.
  UserId author = 3 [(required) = true, (validate) = true];

  // The username shown beside the message.
  string username = 4 [(required) = true];

  // The text written in the posted message.
  string text = 5 [(required) = true];

  // The time at which the message was posted.
  google.protobuf.Timestamp posted_at = 6 [(required) = true];
}
