/*
 * Generated by Spine TypeScript. Do not edit manually.
 * Source Proto: spine/examples/messageboard/message_board.proto
 */

import { TypeRegistry } from "@spine-event-engine/core";
import { messageBoardProtoModule as model0 } from "@spine-event-engine/example-message-board-model";

/**
 * The application type registry composed from every declared model package.
 * Generated from Proto: spine/examples/messageboard/message_board.proto.
 */
export const typeRegistry: TypeRegistry = TypeRegistry.from(model0);
