export {
  type DeclaredEntityVisibility,
  type DescriptorFieldMetadata,
  DescriptorMetadataError,
  type DescriptorMetadataErrorCode,
  type DescriptorMessageSchema,
  describeEntityMetadata,
  type EntityKind,
  type EntityMetadata,
  type EntityVisibility,
  type FirstFieldRoutingHint,
  isEntitySchema,
} from "./entity-metadata.js";

export {
  Apply,
  Assign,
  Command,
  type HandlerMethodDecorator,
  type HandlerMethodValue,
  React,
  Subscribe,
  materializeDecoratedEntityHandlers,
} from "./handler-decorators.js";

export {
  type BaseHandlerMetadata,
  type CommandAssignmentHandlerMetadata,
  type CommandReactionHandlerMetadata,
  type EntityClass,
  type EntityHandlersMetadata,
  type EventApplicationHandlerMetadata,
  type EventApplicationOptions,
  type EventReactionHandlerMetadata,
  type EventSubscriptionHandlerMetadata,
  type HandlerKind,
  type HandlerMetadata,
  HandlerMetadataError,
  type HandlerMetadataErrorCode,
  HandlerMetadataRegistry,
  HandlerMetadataRegistryError,
  type HandlerMetadataRegistryErrorCode,
  type HandlerMetadataRegistryLookup,
  type HandlerMethodName,
  type HandlerRegistrationBuilder,
  type RegisteredHandlerMetadata,
  defineEntityHandlers,
} from "./handler-metadata.js";
