/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
import { describe, expect, it } from "vitest";

import { COPYRIGHT_HEADER, checkCopyright, gitComparison, gitFiles } from "./check-copyright.mjs";

const path = "packages/core/src/example.ts";
const body = "export const example = true;\n";
const compliantHeader = `${COPYRIGHT_HEADER}\n`;
const currentHeader = (year) =>
  `${COPYRIGHT_HEADER.replace("Copyright 2026", `Copyright ${year}`)}\n`;
const options = (files, contents, additions = {}) => ({
  files,
  readFile: (file) => contents[file],
  readManifest: () => ({ sources: [], ownedSources: [] }),
  ...additions,
});

describe("copyright checker", () => {
  it("treats known generated TypeScript as generated rather than authored", () => {
    const path = "examples/todo/generated/spine/examples/todo/tasks_pb.ts";
    const notice =
      "/*\n * Generated by Spine TypeScript. Do not edit manually.\n * Source Proto: spine/examples/todo/tasks.proto\n */\n";

    expect(checkCopyright(options([path], { [path]: notice }))).toEqual([]);
    expect(checkCopyright(options([path], { [path]: `${COPYRIGHT_HEADER}\n${notice}` }))).toEqual([
      `${path}: forbidden CodeMatters header`,
    ]);
  });

  it("requires the approved header at byte zero for an authored TypeScript source", () => {
    const problems = checkCopyright({
      files: ["packages/core/src/example.ts"],
      readFile: () => "export const example = true;\n",
      readManifest: () => ({ sources: [], ownedSources: [] }),
      year: 2026,
    });

    expect(problems).toEqual(["packages/core/src/example.ts: missing CodeMatters header"]);
  });

  it("accepts the exact approved header and rejects a stale year", () => {
    const fresh = `${COPYRIGHT_HEADER}\nexport const example = true;\n`;
    const stale = fresh.replace("Copyright 2026", "Copyright 2025");
    const options = {
      files: ["packages/core/src/example.ts"],
      readManifest: () => ({ sources: [], ownedSources: [] }),
      year: 2026,
    };

    expect(checkCopyright({ ...options, readFile: () => fresh })).toEqual([]);
    expect(checkCopyright({ ...options, readFile: () => stale })).toEqual([
      "packages/core/src/example.ts: stale-year CodeMatters header",
    ]);
  });

  it("requires exactly one empty line after eligible TypeScript and TSX headers", () => {
    const tsx = "packages/client-react/src/view.tsx";
    expect(
      checkCopyright(
        options(
          [path, tsx],
          {
            [path]: `${COPYRIGHT_HEADER}export const example = true;\n`,
            [tsx]: `${COPYRIGHT_HEADER}\n \t\nexport const View = () => null;\n`,
          },
          { year: 2026 },
        ),
      ),
    ).toEqual([
      `${tsx}: incorrect CodeMatters header spacing (expected exactly one empty line)`,
      `${path}: incorrect CodeMatters header spacing (expected exactly one empty line)`,
    ]);
  });

  it("does not advance the year for spacing-only future-year corrections", () => {
    const current = `${compliantHeader}${body}`;
    for (const spacing of ["", "\n\n", " \t\n", "\n \t\n"]) {
      expect(
        checkCopyright(
          options(
            [path],
            { [path]: current },
            { year: 2027, baseContent: () => `${COPYRIGHT_HEADER}${spacing}${body}` },
          ),
        ),
      ).toEqual([]);
    }
  });

  it("places a TypeScript header after a shebang and Proto before syntax", () => {
    const options = {
      readManifest: () => ({ sources: [], ownedSources: [] }),
      year: 2026,
    };

    expect(
      checkCopyright({
        ...options,
        files: ["scripts/tool.ts", "packages/proto/proto/example.proto"],
        readFile: (path) =>
          path.endsWith(".ts")
            ? `#!/usr/bin/env node\n${compliantHeader}export {};\n`
            : `${COPYRIGHT_HEADER}syntax = "proto3";\n`,
      }),
    ).toEqual([]);
  });

  it("preserves upstream provenance exclusions and reports forbidden headers", () => {
    const path = "packages/proto/proto/upstream.proto";
    expect(
      checkCopyright({
        files: [path],
        readFile: () => `${COPYRIGHT_HEADER}syntax = "proto3";\n`,
        readManifest: () => ({ sources: [path], ownedSources: [] }),
        year: 2026,
      }),
    ).toEqual([`${path}: forbidden CodeMatters header`]);
  });

  it("requires the current year only for new or content-changed future files", () => {
    const old = `${compliantHeader}${body}`;
    expect(
      checkCopyright(options([path], { [path]: old }, { year: 2027, baseContent: () => old })),
    ).toEqual([]);
    expect(
      checkCopyright(
        options([path], { [path]: old }, { year: 2027, baseContent: () => undefined }),
      ),
    ).toEqual([`${path}: stale-year CodeMatters header`]);
    expect(
      checkCopyright(
        options(
          [path],
          { [path]: `${compliantHeader}export const example = false;\n` },
          { year: 2027, baseContent: () => old },
        ),
      ),
    ).toEqual([`${path}: stale-year CodeMatters header`]);
    expect(
      checkCopyright(
        options(
          [path],
          { [path]: `${currentHeader(2027)}${body}` },
          { year: 2027, baseContent: () => old },
        ),
      ),
    ).toEqual([]);
  });

  it("does not advance the year for a header-only edit or a unique renamed match", () => {
    const old = `${compliantHeader}${body}`;
    expect(
      checkCopyright(
        options(
          [path],
          { [path]: `${currentHeader(2027)}${body}` },
          { year: 2027, baseContent: () => old },
        ),
      ),
    ).toEqual([]);
    expect(
      checkCopyright(
        options(
          ["packages/core/src/renamed.ts"],
          { "packages/core/src/renamed.ts": old },
          {
            year: 2027,
            baseContent: () => undefined,
            renamedFrom: () => [path],
            baseContentAt: (oldPath) => (oldPath === path ? old : undefined),
          },
        ),
      ),
    ).toEqual([]);
  });

  it("uses the deleted-base fallback for an unstaged untracked rename and fails closed when ambiguous", () => {
    const old = `${compliantHeader}${body}`;
    const renamed = "packages/core/src/renamed.ts";
    const unique = options(
      [renamed],
      { [renamed]: old },
      {
        year: 2027,
        baseContent: () => undefined,
        renamedFrom: () => [],
        deletedBasePaths: () => [path],
        baseContentAt: () => old,
      },
    );
    expect(checkCopyright(unique)).toEqual([]);
    expect(
      checkCopyright({ ...unique, deletedBasePaths: () => [path, "packages/core/src/copy.ts"] }),
    ).toEqual([`${renamed}: ambiguous header-normalized rename match`]);
  });

  it("reports a recognized header after a leading comment as misplaced", () => {
    expect(
      checkCopyright(
        options(
          [path],
          { [path]: `// generated file\n${COPYRIGHT_HEADER}${body}` },
          { year: 2026 },
        ),
      ),
    ).toEqual([`${path}: misplaced CodeMatters header`]);
  });

  it("reports a recognized header after a leading block comment as misplaced", () => {
    expect(
      checkCopyright(
        options([path], { [path]: `/* generated */\n${COPYRIGHT_HEADER}${body}` }, { year: 2026 }),
      ),
    ).toEqual([`${path}: misplaced CodeMatters header`]);
  });

  it("sorts diagnostic classes and fails closed when Git enumeration fails", () => {
    const proto = "packages/proto/proto/upstream.proto";
    expect(
      checkCopyright({
        ...options([path, proto], {
          [path]: `x${COPYRIGHT_HEADER}${body}`,
          [proto]: 'syntax = "proto3";\n',
        }),
        readManifest: () => ({ sources: [proto], ownedSources: [] }),
        year: 2026,
      }),
    ).toEqual([
      `${path}: misplaced CodeMatters header`,
      `${proto}: missing upstream copyright notice`,
    ]);
    expect(() => gitFiles(() => ({ status: 1, stdout: "" }))).toThrow(
      "copyright enumeration failed",
    );
    expect(() => gitComparison(() => ({ status: 1, stdout: "" }))).toThrow(
      "copyright merge-base failed",
    );
  });

  it("checks authored TSX files and distinguishes malformed CodeMatters notices", () => {
    const tsx = "packages/client-react/src/view.tsx";
    expect(
      checkCopyright(
        options(
          [tsx],
          { [tsx]: `${compliantHeader}export const View = () => null;\n` },
          { year: 2026 },
        ),
      ),
    ).toEqual([]);
    expect(
      checkCopyright(
        options(
          [tsx],
          { [tsx]: "/* Copyright 2026, CodeMatters. */\nexport {};\n" },
          { year: 2026 },
        ),
      ),
    ).toEqual([`${tsx}: malformed CodeMatters header`]);
  });

  it("reports an altered approved-header body as malformed rather than stale-year", () => {
    expect(
      checkCopyright(
        options(
          [path],
          { [path]: `${COPYRIGHT_HEADER.replace("AS IS", "AS-IS")}${body}` },
          { year: 2027 },
        ),
      ),
    ).toEqual([`${path}: malformed CodeMatters header`]);
  });

  it("combines committed, staged, and unstaged rename/deletion Git inputs", () => {
    const old = `${compliantHeader}${body}`;
    const responses = new Map([
      ["merge-base origin/main HEAD", "base\n"],
      ["diff --name-status -M base...HEAD", "R100\told-committed.ts\tnew-committed.ts\n"],
      ["diff --name-status -M", "R100\told-unstaged.ts\tnew-unstaged.ts\n"],
      ["diff --cached --name-status -M", "R100\told-staged.ts\tnew-staged.ts\n"],
      ["diff --name-only --diff-filter=D base...HEAD", "deleted-untracked.ts\n"],
      ["diff --name-only --diff-filter=D", "old-unstaged.ts\n"],
      ["diff --cached --name-only --diff-filter=D", "old-staged.ts\n"],
    ]);
    const comparison = gitComparison((args) => {
      const key = args.join(" ");
      if (key.startsWith("show base:")) return { status: 0, stdout: old };
      return { status: 0, stdout: responses.get(key) ?? "" };
    });
    const files = ["new-committed.ts", "new-staged.ts", "new-unstaged.ts", "new-untracked.ts"];
    expect(
      checkCopyright({
        ...options(files, Object.fromEntries(files.map((file) => [file, old])), { year: 2027 }),
        ...comparison,
      }),
    ).toEqual([]);
  });

  it("falls back to origin/master when origin/main is unavailable", () => {
    const calls = [];
    const comparison = gitComparison((args) => {
      calls.push(args);
      if (args.join(" ") === "merge-base origin/main HEAD") return { status: 128, stdout: "" };
      if (args.join(" ") === "merge-base origin/master HEAD")
        return { status: 0, stdout: "base\n" };
      return { status: 0, stdout: "" };
    });

    expect(comparison.deletedBasePaths()).toEqual([]);
    expect(calls.slice(0, 2)).toEqual([
      ["merge-base", "origin/main", "HEAD"],
      ["merge-base", "origin/master", "HEAD"],
    ]);
  });

  it("does not make a single rename ambiguous when Git reports it in multiple comparisons", () => {
    const old = `${compliantHeader}${body}`;
    const comparison = gitComparison((args) => {
      if (args[0] === "merge-base") return { status: 0, stdout: "base\n" };
      if (args.join(" ").includes("--name-status"))
        return { status: 0, stdout: "R100\0old.ts\0renamed.ts\0" };
      if (args.join(" ") === "show base:renamed.ts") return { status: 128, stdout: "" };
      if (args[0] === "show") return { status: 0, stdout: old };
      return { status: 0, stdout: "" };
    });
    expect(
      checkCopyright({
        ...options(["renamed.ts"], { "renamed.ts": old }, { year: 2027 }),
        ...comparison,
      }),
    ).toEqual([]);
  });

  it("treats a Git copy as a new current-year file rather than historical content", () => {
    const old = `${compliantHeader}${body}`;
    const copied = "copied.ts";
    const comparison = gitComparison((args) => {
      if (args[0] === "merge-base") return { status: 0, stdout: "base\n" };
      if (args.join(" ").includes("--name-status"))
        return {
          status: 0,
          stdout: "C100\0original.ts\0copied.ts\0R100\0old.ts\0renamed.ts\0",
        };
      if (args.join(" ") === "show base:copied.ts") return { status: 128, stdout: "" };
      if (args[0] === "show") return { status: 0, stdout: old };
      return { status: 0, stdout: "" };
    });

    expect(
      checkCopyright({
        ...options([copied], { [copied]: old }, { year: 2027 }),
        ...comparison,
      }),
    ).toEqual([`${copied}: stale-year CodeMatters header`]);
    expect(comparison.renamedFrom("renamed.ts")).toEqual(["old.ts"]);
    expect(comparison.renamedFrom(copied)).toEqual([]);
  });

  it("preserves hostile legal Git paths from NUL-delimited output", () => {
    const hostile = ["tab\tname.ts", "line\nbreak.ts", 'quote".tsx', "日本語.proto"];
    expect(gitFiles(() => ({ status: 0, stdout: `${hostile.join("\0")}\0` }))).toEqual(hostile);
  });

  it("parses mixed ordinary and renamed NUL name-status records", () => {
    const renamed = 'new\tline\n"日本語.ts';
    const prior = 'old\tline\n"日本語.ts';
    const deleted = "deleted\nfile.ts";
    const comparison = gitComparison((args) => {
      if (args[0] === "merge-base") return { status: 0, stdout: "base\n" };
      if (args.join(" ").includes("--name-status"))
        return { status: 0, stdout: `M\0ordinary.ts\0R100\0${prior}\0${renamed}\0` };
      if (args.join(" ").includes("--diff-filter=D")) return { status: 0, stdout: `${deleted}\0` };
      if (args[0] === "show") return { status: 0, stdout: `${compliantHeader}${body}` };
      return { status: 0, stdout: "" };
    });
    expect(comparison.renamedFrom(renamed)).toEqual([prior]);
    expect(comparison.deletedBasePaths()).toEqual([deleted]);
  });

  it("fails closed when rename, deletion, or base lookup Git operations fail", () => {
    expect(() =>
      gitComparison((args) =>
        args[0] === "merge-base" ? { status: 0, stdout: "base\n" } : { status: 1, stdout: "" },
      ),
    ).toThrow("copyright rename detection failed");
    const comparison = gitComparison((args) => {
      if (args[0] === "merge-base") return { status: 0, stdout: "base\n" };
      if (args[0] === "show") return { status: 1, stdout: "" };
      return { status: 0, stdout: "" };
    });
    expect(
      checkCopyright({
        ...options([path], { [path]: `${compliantHeader}${body}` }, { year: 2027 }),
        ...comparison,
      }),
    ).toEqual([`${path}: base content lookup failed`]);
  });
});
