import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { publishFixtureModule, renderFixtureModule } from "./generate-server-test-fixtures.mjs";

const scriptPath = fileURLToPath(new URL("./generate-server-test-fixtures.mjs", import.meta.url));
const repoRoot = fileURLToPath(new URL("..", import.meta.url));

describe("generate-server-test-fixtures", () => {
  it("renders generated provenance rather than a CodeMatters header", () => {
    expect(renderFixtureModule(2027)).toMatch(
      /^\/\*\n \* Generated by Spine TypeScript\. Do not edit manually\.\n \* Source Proto: packages\/server\/test-fixtures\/proto\/entity-metadata\/empty\.proto/u,
    );
    expect(renderFixtureModule(2027)).not.toContain("CodeMatters");
    expect(renderFixtureModule()).toContain(
      "/**\n * Generated from Proto: packages/server/test-fixtures/proto/entity-metadata/empty.proto",
    );
  });

  it("keeps checked-in descriptor blobs synchronized with readable proto sources", () => {
    const result = spawnSync(process.execPath, [scriptPath, "--check"], {
      cwd: repoRoot,
      encoding: "utf8",
    });

    expect(result.status).toBe(0);
    expect(result.stderr).toBe("");
  });

  it("cleans descriptor and bootstrap resources when Buf descriptor generation fails", () => {
    const temporary = mkdtempSync(join(tmpdir(), "spine-server-fixtures-failure-"));
    expect(() =>
      renderFixtureModule({
        tempRoot: temporary,
        spawn: () => ({ status: 1, stderr: "Buf unavailable" }),
      }),
    ).toThrow("Server fixture descriptor build failed: Buf unavailable");
    expect(existsSync(temporary)).toBe(false);
    expect(
      readdirSync(join(repoRoot, "packages/proto-tools/node_modules/.cache"), {
        encoding: "utf8",
      }),
    ).not.toContainEqual(expect.stringMatching(/^spine-proto-tools-bootstrap-/u));
  });

  it("runs standalone from an isolated clean proto-tools build output", () => {
    const root = process.cwd();
    const isolated = mkdtempSync(join(tmpdir(), "spine-fixture-clean-bootstrap-"));
    const clone = join(isolated, "repo");
    const worktree = spawnSync("git", ["worktree", "add", "--detach", clone, "HEAD"], {
      cwd: root,
      encoding: "utf8",
    });
    if (worktree.status !== 0) throw new Error(`${worktree.stdout}${worktree.stderr}`);
    try {
      const install = spawnSync("pnpm", ["install", "--offline", "--frozen-lockfile"], {
        cwd: clone,
        encoding: "utf8",
      });
      if (install.status !== 0) throw new Error(`${install.stdout}${install.stderr}`);
      rmSync(join(clone, "packages/proto-tools/dist"), { recursive: true, force: true });
      const result = spawnSync(
        process.execPath,
        [join(clone, "scripts/generate-server-test-fixtures.mjs"), "--check"],
        {
          cwd: clone,
          encoding: "utf8",
        },
      );
      expect(result.status).toBe(0);
      const cache = join(clone, "packages/proto-tools/node_modules/.cache");
      expect(existsSync(cache) ? readdirSync(cache) : []).not.toContainEqual(
        expect.stringMatching(/^spine-proto-tools-bootstrap-/u),
      );
    } finally {
      spawnSync("git", ["worktree", "remove", "--force", clone], { cwd: root, encoding: "utf8" });
      rmSync(isolated, { recursive: true, force: true });
    }
  }, 120_000);

  it("preserves the prior fixture when atomic publication fails", () => {
    const directory = mkdtempSync(join(tmpdir(), "spine-fixture-publication-"));
    const target = join(directory, "fixture.ts");
    writeFileSync(target, "prior\n");
    expect(() =>
      publishFixtureModule(target, "next\n", {
        rename: () => {
          throw new Error("rename failed");
        },
      }),
    ).toThrow("rename failed");
    expect(readFileSync(target, "utf8")).toBe("prior\n");
    expect(readdirSync(directory).some((name) => name.startsWith(".fixture.ts.stage-"))).toBe(
      false,
    );
  });

  it("removes its stage when writing the replacement fixture fails", () => {
    const directory = mkdtempSync(join(tmpdir(), "spine-fixture-write-failure-"));
    try {
      const target = join(directory, "fixture.ts");
      expect(() =>
        publishFixtureModule(target, "next\n", {
          write: () => {
            throw new Error("write failed");
          },
        }),
      ).toThrow("write failed");
      expect(readdirSync(directory)).toEqual([]);
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
