import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { publishFixtureModule, renderFixtureModule } from "./generate-server-test-fixtures.mjs";

const scriptPath = fileURLToPath(new URL("./generate-server-test-fixtures.mjs", import.meta.url));
const repoRoot = fileURLToPath(new URL("..", import.meta.url));

describe("generate-server-test-fixtures", () => {
  it("renders generated provenance rather than a CodeMatters header", () => {
    expect(renderFixtureModule(2027)).toMatch(
      /^\/\*\n \* Generated by Spine TypeScript\. Do not edit manually\.\n \* Source Proto: packages\/server\/test-fixtures\/proto\/entity-metadata\/empty\.proto/u,
    );
    expect(renderFixtureModule(2027)).not.toContain("CodeMatters");
    expect(renderFixtureModule()).toContain(
      "/**\n * Generated from Proto: packages/server/test-fixtures/proto/entity-metadata/empty.proto",
    );
  });

  it("keeps checked-in descriptor blobs synchronized with readable proto sources", () => {
    const result = spawnSync(process.execPath, [scriptPath, "--check"], {
      cwd: repoRoot,
      encoding: "utf8",
    });

    expect(result.status).toBe(0);
    expect(result.stderr).toBe("");
  });

  it("preserves the prior fixture when atomic publication fails", () => {
    const directory = mkdtempSync(join(tmpdir(), "spine-fixture-publication-"));
    const target = join(directory, "fixture.ts");
    writeFileSync(target, "prior\n");
    expect(() =>
      publishFixtureModule(target, "next\n", {
        rename: () => {
          throw new Error("rename failed");
        },
      }),
    ).toThrow("rename failed");
    expect(readFileSync(target, "utf8")).toBe("prior\n");
    expect(readdirSync(directory).some((name) => name.startsWith(".fixture.ts.stage-"))).toBe(
      false,
    );
  });
});
