import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { publishFixtureModule, renderFixtureModule } from "./generate-server-test-fixtures.mjs";

const scriptPath = fileURLToPath(new URL("./generate-server-test-fixtures.mjs", import.meta.url));
const repoRoot = fileURLToPath(new URL("..", import.meta.url));

describe("generate-server-test-fixtures", () => {
  it("renders generated provenance rather than a CodeMatters header", () => {
    expect(renderFixtureModule(2027)).toMatch(
      /^\/\*\n \* Generated by Spine TypeScript\. Do not edit manually\.\n \* Source Proto: packages\/server\/test-fixtures\/proto\/entity-metadata\/empty\.proto/u,
    );
    expect(renderFixtureModule(2027)).not.toContain("CodeMatters");
    expect(renderFixtureModule()).toContain(
      "/**\n * Generated from Proto: packages/server/test-fixtures/proto/entity-metadata/empty.proto",
    );
  });

  it("keeps checked-in descriptor blobs synchronized with readable proto sources", () => {
    const result = spawnSync(process.execPath, [scriptPath, "--check"], {
      cwd: repoRoot,
      encoding: "utf8",
    });

    expect(result.status).toBe(0);
    expect(result.stderr).toBe("");
  });

  it("preserves the prior fixture when atomic publication fails", () => {
    const writes = [];
    expect(() =>
      publishFixtureModule("fixture.ts", "next", {
        write: (path, source) => writes.push([path, source]),
        rename: () => {
          throw new Error("rename failed");
        },
        remove: (path) => writes.push(["remove", path]),
      }),
    ).toThrow("rename failed");
    expect(writes.at(-1)).toEqual(["remove", expect.stringContaining(".stage-")]);
  });
});
