import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { generatedFileNotice, generatedTypeScript } from "./generated-source-policy.mjs";

describe("generated source policy", () => {
  it("removes a copied Proto copyright notice while retaining stable provenance", () => {
    const source = [
      "//",
      "// Copyright 2026, CodeMatters. All rights reserved.",
      "//",
      '// Licensed under the Apache License, Version 2.0 (the "License");',
      "// @generated from file spine/example/task.proto",
      "export const Task = true;",
      "",
    ].join("\n");

    expect(generatedTypeScript(source, ["spine/example/task.proto"])).toBe(
      [
        "/*",
        " * Generated by Spine TypeScript. Do not edit manually.",
        " * Source Proto: spine/example/task.proto",
        " */",
        "",
        "// @generated from file spine/example/task.proto",
        "/**",
        " * Generated from Proto: spine/example/task.proto.",
        " */",
        "export const Task = true;",
        "",
      ].join("\n"),
    );
  });

  it("rejects unstable or machine-local Proto provenance", () => {
    for (const value of [
      "",
      "../task.proto",
      "/tmp/task.proto",
      "C:\\work\\task.proto",
      ".generated-stage/task.proto",
      ".stage-123/task.proto",
      ".backup-prior/task.proto",
      "tmp/task.proto",
      "temp/task.proto",
    ]) {
      expect(() => generatedFileNotice([value])).toThrow(/stable Proto provenance/);
    }
    expect(generatedFileNotice(["template/task.proto", "attempt/task.proto"])).toContain(
      "Source Proto: template/task.proto",
    );
  });

  it("documents exported interfaces, enums, types, and constants", () => {
    const source = [
      "export interface Task {}",
      "export enum State { Open }",
      "export type TaskId = string;",
      "export const task = true;",
      "",
    ].join("\n");
    const generated = generatedTypeScript(source, ["spine/example/task.proto"]);
    expect(generated.match(/Generated from Proto:/gu)).toHaveLength(4);
  });

  it("keeps every ignored example Proto module singly noticed and documented", () => {
    for (const example of ["todo", "projects", "orders", "message-board/model"]) {
      const source = readFileSync(
        join(process.cwd(), "examples", example, "generated/proto-module.ts"),
        "utf8",
      );
      expect(source.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
      expect(source.match(/Generated from Proto:/gu)).toHaveLength(1);
      expect(source).not.toContain("CodeMatters");
      const protoSources = [...source.matchAll(/^ \* Source Proto: (.+)$/gmu)].map(
        (match) => match[1],
      );
      expect(protoSources).not.toContainEqual(expect.stringMatching(/^(?:\/|[A-Za-z]:\\)/u));
      const declaration = readFileSync(
        join(process.cwd(), "examples", example, "dist/generated/proto-module.d.ts"),
        "utf8",
      );
      expect(declaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
      expect(declaration.match(/Generated from Proto:/gu)).toHaveLength(1);
      expect(declaration).not.toContain("CodeMatters");
    }
  });
});
