import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import {
  generatedFileNotice,
  generatedTypeScript,
  sourceProtoForGeneratedFile,
} from "./generated-source-policy.mjs";

describe("generated source policy", () => {
  it("keeps generated TypeScript inventories free of copied copyright and license preambles", () => {
    const roots = [
      "packages/proto/generated",
      "packages/proto/dist/generated",
      "examples/todo/generated",
      "examples/todo/dist/generated",
      "examples/projects/generated",
      "examples/projects/dist/generated",
      "examples/orders/generated",
      "examples/orders/dist/generated",
      "examples/message-board/model/generated",
      "examples/message-board/model/dist/generated",
      "examples/message-board/app/generated/handler",
      "examples/message-board/app/dist/generated",
    ];
    const files = [
      "examples/message-board/app/src/model-registry.ts",
      "examples/message-board/app/dist/src/model-registry.d.ts",
      "packages/server/test-fixtures/entity-metadata-fixtures.ts",
    ].map((path) => join(process.cwd(), path));
    for (const root of roots) {
      const directoryRoot = join(process.cwd(), root);
      if (!existsSync(directoryRoot)) continue;
      const before = files.length;
      const pending = [directoryRoot];
      while (pending.length > 0) {
        const directory = pending.pop();
        for (const entry of readdirSync(directory, { withFileTypes: true })) {
          const path = join(directory, entry.name);
          if (entry.isDirectory()) pending.push(path);
          else if (entry.isFile() && /\.(?:d\.ts|ts)$/u.test(path)) files.push(path);
        }
      }
      expect(files.length).toBeGreaterThan(before);
    }
    for (const file of files)
      expect(readFileSync(file, "utf8")).not.toMatch(
        /copyright|all rights reserved|proprietary and confidential|licensed under/iu,
      );
  });

  it("removes a copied Proto copyright notice while retaining stable provenance", () => {
    const source = [
      "//",
      "// Copyright 2026, CodeMatters. All rights reserved.",
      "//",
      '// Licensed under the Apache License, Version 2.0 (the "License");',
      "// @generated from file spine/example/task.proto",
      "export const Task = true;",
      "",
    ].join("\n");

    expect(generatedTypeScript(source, ["spine/example/task.proto"])).toBe(
      [
        "/*",
        " * Generated by Spine TypeScript. Do not edit manually.",
        " * Source Proto: spine/example/task.proto",
        " */",
        "",
        "// @generated from file spine/example/task.proto",
        "/**",
        " * Generated from Proto: spine/example/task.proto.",
        " */",
        "export const Task = true;",
        "",
      ].join("\n"),
    );
  });

  it("removes copied upstream block and line copyright preambles", () => {
    const source = [
      "/* Copyright 2024 TeamDev Ltd. Licensed under Apache-2.0. */",
      "// Copyright 2023 Upstream Authors",
      "// Licensed under the Apache License, Version 2.0",
      "// @generated from file spine/example/task.proto",
      "export const Task = true;",
      "",
    ].join("\n");

    const generated = generatedTypeScript(source, ["spine/example/task.proto"]);
    expect(generated).not.toMatch(/copyright|TeamDev|Upstream Authors/iu);
    expect(generated).toContain("// @generated from file spine/example/task.proto");
  });

  it("preserves generated metadata while removing a copied line copyright preamble", () => {
    const source = [
      "// Copyright 2024 TeamDev",
      "// Licensed under terms",
      "// @generated from file spine/example/task.proto",
      "export const Task = true;",
    ].join("\n");
    expect(generatedTypeScript(source, ["spine/example/task.proto"])).toContain(
      "// @generated from file spine/example/task.proto",
    );
  });

  it("derives Proto provenance from generated file naming variants", () => {
    expect(sourceProtoForGeneratedFile("spine\\task_pb.ts")).toBe("spine/task.proto");
    expect(sourceProtoForGeneratedFile("spine/task_columns.ts")).toBe("spine/task.proto");
    expect(sourceProtoForGeneratedFile("spine/registry.ts")).toBe("spine/registry.proto");
  });

  it("rejects unstable or machine-local Proto provenance", () => {
    for (const value of [
      "",
      "../task.proto",
      "/tmp/task.proto",
      "C:\\work\\task.proto",
      ".generated-stage/task.proto",
      ".stage-123/task.proto",
      ".backup-prior/task.proto",
      "tmp/task.proto",
      "temp/task.proto",
    ]) {
      expect(() => generatedFileNotice([value])).toThrow(/stable Proto provenance/);
    }
    expect(generatedFileNotice(["template/task.proto", "attempt/task.proto"])).toContain(
      "Source Proto: template/task.proto",
    );
  });

  it("documents exported interfaces, enums, types, and constants", () => {
    const source = [
      "export interface Task {}",
      "export enum State { Open }",
      "export type TaskId = string;",
      "export const task = true;",
      "",
    ].join("\n");
    const generated = generatedTypeScript(source, ["spine/example/task.proto"]);
    expect(generated.match(/Generated from Proto:/gu)).toHaveLength(4);
  });

  it("keeps every ignored example Proto module singly noticed and documented", () => {
    for (const example of ["todo", "projects", "orders", "message-board/model"]) {
      const source = readFileSync(
        join(process.cwd(), "examples", example, "generated/proto-module.ts"),
        "utf8",
      );
      expect(source.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
      expect(source.match(/Generated from Proto:/gu)).toHaveLength(1);
      expect(source).not.toContain("CodeMatters");
      const protoSources = [...source.matchAll(/^ \* Source Proto: (.+)$/gmu)].map(
        (match) => match[1],
      );
      expect(protoSources).not.toContainEqual(expect.stringMatching(/^(?:\/|[A-Za-z]:\\)/u));
      const declaration = readFileSync(
        join(process.cwd(), "examples", example, "dist/generated/proto-module.d.ts"),
        "utf8",
      );
      expect(declaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
      expect(declaration.match(/Generated from Proto:/gu)).toHaveLength(1);
      expect(declaration).not.toContain("CodeMatters");
    }
    const frameworkDeclaration = readFileSync(
      join(process.cwd(), "packages/proto/dist/generated/proto-module.d.ts"),
      "utf8",
    );
    expect(frameworkDeclaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
    expect(frameworkDeclaration.match(/Generated from Proto:/gu)).toHaveLength(1);
    expect(frameworkDeclaration).not.toContain("CodeMatters");

    const appDeclaration = readFileSync(
      join(process.cwd(), "examples/message-board/app/dist/src/model-registry.d.ts"),
      "utf8",
    );
    expect(appDeclaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
    expect(appDeclaration.match(/Generated from Proto:/gu)).toHaveLength(1);
    expect(appDeclaration).not.toContain("CodeMatters");
  });
});
