/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { normalizeGeneratedDeclarations } from "./normalize-generated-declarations.mjs";

describe("generated declaration normalization", () => {
  it("has no import side effect and normalizes only through its CLI entrypoint", () => {
    const root = process.cwd();
    const isolated = mkdtempSync(join(tmpdir(), "spine-declaration-cli-"));
    const clone = join(isolated, "repo");
    const worktree = spawnSync("git", ["worktree", "add", "--detach", clone, "HEAD"], {
      cwd: root,
      encoding: "utf8",
    });
    if (worktree.status !== 0) throw new Error(`${worktree.stdout}${worktree.stderr}`);
    try {
      const install = spawnSync("pnpm", ["install", "--offline", "--frozen-lockfile"], {
        cwd: clone,
        encoding: "utf8",
      });
      if (install.status !== 0) throw new Error(`${install.stdout}${install.stderr}`);
      const generated = join(clone, "examples/todo/generated");
      const dist = join(clone, "examples/todo/dist/generated");
      mkdirSync(generated, { recursive: true });
      mkdirSync(dist, { recursive: true });
      writeFileSync(
        join(generated, "proto-module.ts"),
        "/*\n * Generated by Spine TypeScript. Do not edit manually.\n * Source Proto: example/task.proto\n */\n\nexport const module = true;\n",
      );
      const declaration = join(dist, "proto-module.d.ts");
      writeFileSync(declaration, "export declare const module: boolean;\n");
      const imported = spawnSync(
        process.execPath,
        ["--input-type=module", "-e", 'import "./scripts/normalize-generated-declarations.mjs"'],
        { cwd: clone, encoding: "utf8" },
      );
      if (imported.status !== 0) throw new Error(`${imported.stdout}${imported.stderr}`);
      expect(readFileSync(declaration, "utf8")).toBe("export declare const module: boolean;\n");
      const cli = spawnSync(process.execPath, ["scripts/normalize-generated-declarations.mjs"], {
        cwd: clone,
        encoding: "utf8",
      });
      expect(cli.status).toBe(0);
      expect(readFileSync(declaration, "utf8")).toContain(
        "Generated from Proto: example/task.proto.",
      );
    } finally {
      spawnSync("git", ["worktree", "remove", "--force", clone], { cwd: root, encoding: "utf8" });
      rmSync(isolated, { recursive: true, force: true });
    }
  }, 120_000);

  it("normalizes module and handler declarations idempotently and skips absent roots", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-policy-"));
    try {
      const generated = join(root, "fixture", "generated");
      const dist = join(root, "fixture", "dist", "generated");
      mkdirSync(join(dist, "handler"), { recursive: true });
      mkdirSync(join(generated, "handler"), { recursive: true });
      const notice =
        "/*\n * Generated by Spine TypeScript. Do not edit manually.\n * Source Proto: example/task.proto\n */\n\n";
      writeFileSync(join(generated, "proto-module.ts"), `${notice}export const module = true;\n`);
      writeFileSync(
        join(generated, "handler", "generated-handler-registry.ts"),
        `${notice}export const handlers = true;\n`,
      );
      writeFileSync(join(dist, "proto-module.d.ts"), "export declare const module: boolean;\n");
      writeFileSync(
        join(dist, "handler", "generated-handler-registry.d.ts"),
        "export declare const handlers: boolean;\n",
      );

      normalizeGeneratedDeclarations(root, ["fixture", "absent"]);
      const module = readFileSync(join(dist, "proto-module.d.ts"), "utf8");
      const handler = readFileSync(
        join(dist, "handler", "generated-handler-registry.d.ts"),
        "utf8",
      );
      normalizeGeneratedDeclarations(root, ["fixture", "absent"]);

      for (const declaration of [module, handler]) {
        expect(declaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
        expect(declaration.match(/Generated from Proto:/gu)).toHaveLength(1);
        expect(declaration).not.toContain("CodeMatters");
      }
      expect(readFileSync(join(dist, "proto-module.d.ts"), "utf8")).toBe(module);
      expect(readFileSync(join(dist, "handler", "generated-handler-registry.d.ts"), "utf8")).toBe(
        handler,
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("normalizes generated interface declarations with their Proto provenance", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-interfaces-"));
    try {
      const generated = join(root, "fixture", "generated", "interfaces");
      const dist = join(root, "fixture", "dist", "generated", "interfaces");
      mkdirSync(generated, { recursive: true });
      mkdirSync(dist, { recursive: true });
      const notice =
        "/*\n * Generated by Spine TypeScript. Do not edit manually.\n * Source Proto: example/task-events.proto\n */\n\n";
      writeFileSync(join(generated, "task-event.ts"), `${notice}export interface TaskEvent {}\n`);
      writeFileSync(join(dist, "task-event.d.ts"), "export interface TaskEvent {}\n");

      normalizeGeneratedDeclarations(root, ["fixture"]);

      const declaration = readFileSync(join(dist, "task-event.d.ts"), "utf8");
      expect(declaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
      expect(declaration).toContain("Source Proto: example/task-events.proto");
      expect(declaration).toContain("Generated from Proto: example/task-events.proto.");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("rejects bounded traversal depth", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-depth-"));
    try {
      let directory = join(root, "fixture", "dist", "generated");
      for (let depth = 0; depth < 66; depth += 1) directory = join(directory, "nested");
      mkdirSync(directory, { recursive: true });
      mkdirSync(join(root, "fixture", "generated"), { recursive: true });

      expect(() => normalizeGeneratedDeclarations(root, ["fixture"])).toThrow(/bounded inventory/u);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("rejects bounded traversal entry inventory", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-entries-"));
    try {
      const dist = join(root, "fixture", "dist", "generated");
      mkdirSync(dist, { recursive: true });
      mkdirSync(join(root, "fixture", "generated"), { recursive: true });
      for (let index = 0; index < 1_001; index += 1)
        writeFileSync(join(dist, `entry-${String(index)}.d.ts`), "export {};\n");

      expect(() => normalizeGeneratedDeclarations(root, ["fixture"])).toThrow(/bounded inventory/u);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
