/*
 * Copyright 2026, CodeMatters. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { normalizeGeneratedDeclarations } from "./normalize-generated-declarations.mjs";

describe("generated declaration normalization", () => {
  it("normalizes module and handler declarations idempotently and skips absent roots", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-policy-"));
    try {
      const generated = join(root, "fixture", "generated");
      const dist = join(root, "fixture", "dist", "generated");
      mkdirSync(join(dist, "handler"), { recursive: true });
      mkdirSync(join(generated, "handler"), { recursive: true });
      const notice =
        "/*\n * Generated by Spine TypeScript. Do not edit manually.\n * Source Proto: example/task.proto\n */\n\n";
      writeFileSync(join(generated, "proto-module.ts"), `${notice}export const module = true;\n`);
      writeFileSync(
        join(generated, "handler", "generated-handler-registry.ts"),
        `${notice}export const handlers = true;\n`,
      );
      writeFileSync(join(dist, "proto-module.d.ts"), "export declare const module: boolean;\n");
      writeFileSync(
        join(dist, "handler", "generated-handler-registry.d.ts"),
        "export declare const handlers: boolean;\n",
      );

      normalizeGeneratedDeclarations(root, ["fixture", "absent"]);
      const module = readFileSync(join(dist, "proto-module.d.ts"), "utf8");
      const handler = readFileSync(
        join(dist, "handler", "generated-handler-registry.d.ts"),
        "utf8",
      );
      normalizeGeneratedDeclarations(root, ["fixture", "absent"]);

      for (const declaration of [module, handler]) {
        expect(declaration.match(/Generated by Spine TypeScript/gu)).toHaveLength(1);
        expect(declaration.match(/Generated from Proto:/gu)).toHaveLength(1);
        expect(declaration).not.toContain("CodeMatters");
      }
      expect(readFileSync(join(dist, "proto-module.d.ts"), "utf8")).toBe(module);
      expect(readFileSync(join(dist, "handler", "generated-handler-registry.d.ts"), "utf8")).toBe(
        handler,
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("rejects bounded traversal depth", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-depth-"));
    try {
      let directory = join(root, "fixture", "dist", "generated");
      for (let depth = 0; depth < 66; depth += 1) directory = join(directory, "nested");
      mkdirSync(directory, { recursive: true });
      mkdirSync(join(root, "fixture", "generated"), { recursive: true });

      expect(() => normalizeGeneratedDeclarations(root, ["fixture"])).toThrow(/bounded inventory/u);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("rejects bounded traversal entry inventory", () => {
    const root = mkdtempSync(join(tmpdir(), "spine-declaration-entries-"));
    try {
      const dist = join(root, "fixture", "dist", "generated");
      mkdirSync(dist, { recursive: true });
      mkdirSync(join(root, "fixture", "generated"), { recursive: true });
      for (let index = 0; index < 1_001; index += 1)
        writeFileSync(join(dist, `entry-${String(index)}.d.ts`), "export {};\n");

      expect(() => normalizeGeneratedDeclarations(root, ["fixture"])).toThrow(/bounded inventory/u);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
