import { create } from "@bufbuild/protobuf";
import { TimestampSchema, type Timestamp } from "@bufbuild/protobuf/wkt";
import { randomBytes as nodeRandomBytes } from "node:crypto";

import type {
  AuthenticatedPrincipal,
  CookieCredential,
  RequestCredential,
  ResolvedSession,
  SessionResolver,
} from "../index.js";

/** Clock used to evaluate opaque-session expiry. */
export interface OpaqueSessionClock {
  /**
   * Returns Unix epoch milliseconds as a safe integer in the Protobuf Timestamp range.
   * @returns The current milliseconds.
   */
  now(): number;
}
/**
 * Creates random bytes for an opaque session identifier.
 * @param length The required byte length.
 * @returns The generated bytes.
 */
export type OpaqueSessionRandom = (length: number) => Uint8Array;
/** Construction options for the bounded in-memory opaque-session resolver. */
export interface OpaqueSessionsOptions {
  /** Millisecond clock; each value must be a safe integer in Timestamp range. */
  readonly clock?: OpaqueSessionClock;
  /**
   * Receives exactly `32` and returns exactly 32 random bytes per call.
   * Throwing or wrong-length results consume a bounded collision attempt, and
   * every returned mutable buffer is zeroed before this resolver returns.
   */
  readonly randomBytes?: OpaqueSessionRandom;
  /** Positive safe session lifetime in milliseconds; defaults to eight hours. */
  readonly ttlMilliseconds?: number;
  /** Positive safe retained-session bound; defaults to 10,000. */
  readonly maxSessions?: number;
  /** Positive safe ID-generation attempt bound; defaults to three. */
  readonly collisionAttempts?: number;
}
/** Result of creating an opaque session. */
export type OpaqueSessionCreateResult =
  | {
      /** Identifies successful session creation. */
      readonly kind: "created";
      /** Provides the cookie credential for the created session. */
      readonly credential: CookieCredential;
      /** Provides a defensive copy of the created session. */
      readonly session: ResolvedSession;
    }
  | {
      /** Identifies rejected session creation. */
      readonly kind: "rejected";
      /** Explains why the session could not be created. */
      readonly reason: "capacity-exceeded" | "entropy-exhausted" | "clock-failure" | "closed";
    };
/** Result of rotating an opaque session. */
export type OpaqueSessionRotateResult =
  | {
      /** Identifies successful session rotation. */
      readonly kind: "rotated";
      /** Provides the replacement cookie credential. */
      readonly credential: CookieCredential;
      /** Provides a defensive copy of the replacement session. */
      readonly session: ResolvedSession;
    }
  | {
      /** Identifies rejected session rotation. */
      readonly kind: "rejected";
      /** Explains why the session could not be rotated. */
      readonly reason:
        | "not-found"
        | "expired"
        | "unsupported-credential"
        | "entropy-exhausted"
        | "clock-failure"
        | "closed";
    };
/** Enumeration-safe acknowledgement of an opaque-session logout request. */
export interface OpaqueSessionLogoutResult {
  /** Confirms that the logout request was accepted. */
  readonly kind: "logged-out";
}

/**
 * A bounded, terminal in-memory store of random opaque application sessions.
 *
 * It is intentionally process-local: applications needing durable or shared
 * sessions provide another `SessionResolver` implementation.
 */
export class OpaqueSessions implements SessionResolver {
  private readonly records = new Map<string, SessionRecord>();
  private readonly clock: OpaqueSessionClock;
  private readonly random: OpaqueSessionRandom;
  private readonly ttlMilliseconds: number;
  private readonly maxSessions: number;
  private readonly collisionAttempts: number;
  private closed = false;

  /** Creates a bounded in-memory session store.
   * @param options The optional clock, entropy, lifetime, and capacity settings.
   */
  constructor(options: OpaqueSessionsOptions = {}) {
    this.clock = options.clock ?? { now: Date.now };
    this.random = options.randomBytes ?? nodeRandomBytes;
    this.ttlMilliseconds = OpaqueSessionValues.positiveSafeInteger(
      options.ttlMilliseconds ?? 8 * 60 * 60 * 1_000,
      "ttlMilliseconds",
    );
    this.maxSessions = OpaqueSessionValues.positiveSafeInteger(
      options.maxSessions ?? 10_000,
      "maxSessions",
    );
    this.collisionAttempts = OpaqueSessionValues.positiveSafeInteger(
      options.collisionAttempts ?? 3,
      "collisionAttempts",
    );
  }

  /** Creates a new session unless the terminal or bounded store state rejects it.
   * @param principal The authenticated principal to retain.
   * @returns The creation outcome and, when accepted, credential and session.
   */
  create(principal: AuthenticatedPrincipal): Promise<OpaqueSessionCreateResult> {
    if (this.isClosed()) return Promise.resolve({ kind: "rejected", reason: "closed" });
    const now = this.now();
    if (now === undefined) return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    this.sweepExpired(now);
    if (this.records.size >= this.maxSessions)
      return Promise.resolve({ kind: "rejected", reason: "capacity-exceeded" });
    const id = this.nextId();
    if (id === undefined) return Promise.resolve({ kind: "rejected", reason: "entropy-exhausted" });
    const current = this.now();
    if (current === undefined)
      return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    this.sweepExpired(current);
    if (this.isClosed()) return Promise.resolve({ kind: "rejected", reason: "closed" });
    if (this.records.size >= this.maxSessions) {
      return Promise.resolve({ kind: "rejected", reason: "capacity-exceeded" });
    }
    if (this.records.has(id))
      return Promise.resolve({ kind: "rejected", reason: "entropy-exhausted" });
    const record = this.record(principal, current);
    if (record === undefined) return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    if (this.isClosed()) return Promise.resolve({ kind: "rejected", reason: "closed" });
    this.records.set(id, record);
    return Promise.resolve({
      kind: "created",
      credential: OpaqueSessionValues.credential(id),
      session: OpaqueSessionValues.resolved(record),
    });
  }

  /** Resolves one currently live cookie credential as a defensive copy.
   * @param credentialInput The credential to resolve.
   * @returns The live session, or undefined when it is invalid or expired.
   */
  resolve(credentialInput: RequestCredential): Promise<ResolvedSession | undefined> {
    if (this.closed || credentialInput.kind !== "cookie") return Promise.resolve(undefined);
    const now = this.now();
    if (now === undefined) return Promise.resolve(undefined);
    const record = this.live(credentialInput.value, now);
    return Promise.resolve(record === undefined ? undefined : OpaqueSessionValues.resolved(record));
  }

  /** Updates a live opaque credential without ever retaining both values.
   * @param credentialInput The credential to replace.
   * @returns The rotation outcome and, when accepted, the replacement values.
   */
  rotate(credentialInput: RequestCredential): Promise<OpaqueSessionRotateResult> {
    if (this.isClosed()) return Promise.resolve({ kind: "rejected", reason: "closed" });
    if (credentialInput.kind !== "cookie")
      return Promise.resolve({ kind: "rejected", reason: "unsupported-credential" });
    const now = this.now();
    if (now === undefined) return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    const previous = this.records.get(credentialInput.value);
    if (previous === undefined) return Promise.resolve({ kind: "rejected", reason: "not-found" });
    if (this.expired(previous, now)) {
      this.records.delete(credentialInput.value);
      return Promise.resolve({ kind: "rejected", reason: "expired" });
    }
    const id = this.nextId();
    if (id === undefined) return Promise.resolve({ kind: "rejected", reason: "entropy-exhausted" });
    const current = this.now();
    if (current === undefined)
      return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    if (this.isClosed()) return Promise.resolve({ kind: "rejected", reason: "closed" });
    if (this.records.get(credentialInput.value) !== previous) {
      return Promise.resolve({ kind: "rejected", reason: "not-found" });
    }
    if (this.expired(previous, current)) {
      this.records.delete(credentialInput.value);
      return Promise.resolve({ kind: "rejected", reason: "expired" });
    }
    if (this.records.has(id))
      return Promise.resolve({ kind: "rejected", reason: "entropy-exhausted" });
    const record = this.record(previous.principal, current);
    if (record === undefined) return Promise.resolve({ kind: "rejected", reason: "clock-failure" });
    this.records.delete(credentialInput.value);
    this.records.set(id, record);
    return Promise.resolve({
      kind: "rotated",
      credential: OpaqueSessionValues.credential(id),
      session: OpaqueSessionValues.resolved(record),
    });
  }

  /** Deletes a cookie session when present without revealing whether it existed.
   * @param credentialInput The credential to invalidate.
   * @returns An enumeration-safe logout acknowledgement.
   */
  logout(credentialInput: RequestCredential): Promise<OpaqueSessionLogoutResult> {
    if (!this.closed && credentialInput.kind === "cookie")
      this.records.delete(credentialInput.value);
    return Promise.resolve({ kind: "logged-out" });
  }

  /** Closes the store and drops retained session identity and record references.
   */
  close(): Promise<void> {
    if (this.closed) return Promise.resolve();
    this.closed = true;
    this.records.clear();
    return Promise.resolve();
  }

  private isClosed(): boolean {
    return this.closed;
  }

  private record(principal: AuthenticatedPrincipal, now: number): SessionRecord | undefined {
    const expiresAt = now + this.ttlMilliseconds;
    if (!Number.isSafeInteger(expiresAt) || !OpaqueSessionValues.timestampValid(expiresAt)) {
      this.failClosed();
      return undefined;
    }
    return { principal: OpaqueSessionValues.copyPrincipal(principal), expiresAt };
  }

  private nextId(): string | undefined {
    for (let attempt = 0; attempt < this.collisionAttempts; attempt += 1) {
      let bytes: Uint8Array;
      try {
        bytes = this.random(32);
      } catch {
        continue;
      }
      try {
        if (bytes.byteLength !== 32) continue;
        const id = Buffer.from(bytes).toString("base64url");
        if (!this.records.has(id)) return id;
      } finally {
        bytes.fill(0);
      }
    }
    return undefined;
  }

  private live(id: string, now: number): SessionRecord | undefined {
    const record = this.records.get(id);
    if (record === undefined) return undefined;
    if (!this.expired(record, now)) return record;
    this.records.delete(id);
    return undefined;
  }

  private sweepExpired(now: number): void {
    for (const [id, record] of this.records) if (this.expired(record, now)) this.records.delete(id);
  }

  private expired(record: SessionRecord, now: number): boolean {
    return now >= record.expiresAt;
  }

  private now(): number | undefined {
    try {
      const value = this.clock.now();
      if (!Number.isSafeInteger(value) || !OpaqueSessionValues.timestampValid(value))
        throw new Error("invalid clock");
      return value;
    } catch {
      this.failClosed();
      return undefined;
    }
  }

  private failClosed(): void {
    this.closed = true;
    this.records.clear();
  }
}

interface SessionRecord {
  readonly principal: AuthenticatedPrincipal;
  readonly expiresAt: number;
}

/** Owns opaque-session value checks and immutable value construction. */
const OpaqueSessionValues = Object.freeze({
  positiveSafeInteger(value: number, name: string): number {
    if (!Number.isSafeInteger(value) || value <= 0)
      throw new Error(`${name} must be a positive safe integer`);
    return value;
  },

  credential(value: string): CookieCredential {
    return Object.freeze({ kind: "cookie" as const, value });
  },

  copyPrincipal(principal: AuthenticatedPrincipal): AuthenticatedPrincipal {
    if (typeof principal.id !== "string") throw new Error("principal.id must be a string");
    const attributes =
      principal.attributes === undefined ? undefined : Object.freeze({ ...principal.attributes });
    return Object.freeze(
      attributes === undefined ? { id: principal.id } : { id: principal.id, attributes },
    );
  },

  resolved(record: SessionRecord): ResolvedSession {
    return Object.freeze({
      principal: OpaqueSessionValues.copyPrincipal(record.principal),
      expiresAt: OpaqueSessionValues.timestamp(record.expiresAt),
    });
  },

  timestamp(milliseconds: number): Timestamp {
    const seconds = Math.floor(milliseconds / 1_000);
    return create(TimestampSchema, {
      seconds: BigInt(seconds),
      nanos: (milliseconds - seconds * 1_000) * 1_000_000,
    });
  },

  timestampValid(milliseconds: number): boolean {
    const seconds = Math.floor(milliseconds / 1_000);
    return seconds >= -62_135_596_800 && seconds <= 253_402_300_799;
  },
});
